# Generated by Django 3.2.6 on 2021-08-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210110_1446'),
        ('store', '0007_slugify'),
    ]

    operations = [
    ]
